#!/bin/sh
set -e

dirty=$(git status --porcelain)
if [ "x$dirty" != x ]; then
	git --no-pager status
	echo >&2 '** tree is dirty **'
#	exit 16
fi

git push --dry-run --quiet origin HEAD:published

make clean
make
set -x

rsync -r --delete ../Build/polyglot/html/. \
	ianmdlvl@chiark:public-html/rust-polyglot/.

git push origin HEAD:published
