#!/bin/bash
set -e
set -o pipefail

dirty=$(git status --porcelain)
if [ "x$dirty" != x ]; then
	git --no-pager status
	echo >&2 '** tree is dirty **'
#	exit 16
fi

if [ "x$(git symbolic-ref HEAD 2>/dev/null)" != xrefs/heads/main ]; then
	echo >&2 '** not on main branch **'
	exit 16
fi

git push origin HEAD:main

git push --dry-run --quiet origin HEAD:published

make clean
make html pdf
set -x

rsync -r --delete ../Build/polyglot/html/. polyglot.pdf \
	ianmdlvl@chiark:public-html/rust-polyglot/.

git push origin HEAD:published 2>&1 \
| perl -0777 -pe '
	s{^remote: To create a merge request.*\nremote:.*https:.*\n}{}m;
	s{^(?:remote:[ \t]*\n)*}{};
	s{(^|\n)(?:remote:[ \t]*\n)*{$1}};
'

echo 'published.'
