#!/usr/bin/perl -w
use strict;

my $f = "docs/SUMMARY.md";

open I, "$f" or die $!;
open O, "$f.tmp" or die $!;

my $chapter = qr{^ - \[.*\]\(.*\)\s*$};

while (<I>) {
  last if m{$chapter};
  print or die $!;
}

for $f in <docs/*.md> {
  my $leaf = $f; $leaf =~ s{.*/}{};
  next if $leaf =~ eq 'SUMMARY.md';
  open L, $leaf or die $!;
  my $title = <L> // die $!;
  $title =~ s/\s+$// or die "$leaf ?";
  <L> =~ m{^==+\s*$} or die "$leaf ?";
  print O " - [$title]($leaf)\n" or die $!;
}

while (<I>) {
  last if !m{$chapter};
}
do {
  print or die $!;
} while <I>;
I->error and die $!;
		       
